import { useState } from "react";
import { ArrowDown, ArrowRight, Check, ChevronDown, Clock3, Droplets, Mail, MapPin, Menu, PhoneCall, ShieldCheck, Sparkles, Star, Users, X } from "lucide-react";

const logo = "/fassinou/logo.jpg";
const products = "/fassinou/hero.webp";
const cleaning = "/fassinou/service-cleaning.jpg";
const worker = "/fassinou/service-worker.jpg";
const team = "/fassinou/team.jpg";

const services = [
  { icon: Sparkles, name: "Entretien", text: "Un entretien régulier et soigné pour des espaces toujours impeccables." },
  { icon: Droplets, name: "Nettoyage", text: "Le nettoyage professionnel de vos bureaux, maisons et commerces." },
  { icon: Check, name: "Remise en état", text: "Nous redonnons vie à vos espaces après travaux ou déménagement." },
  { icon: ShieldCheck, name: "Dératisation", text: "Des solutions fiables pour protéger durablement votre environnement." },
  { icon: Users, name: "Désinsectisation", text: "Une hygiène maîtrisée et un accompagnement discret et efficace." },
];

const faqs = [
  ["Quels types de locaux entretenez-vous?", "Fassinou Services intervient dans les maisons, bureaux, commerces, immeubles et espaces professionnels, selon vos besoins."],
  ["Intervenez-vous à Cotonou et ses environs?", "Oui. Nous sommes basés à Haie Vive, dans le 12ème arrondissement de Cotonou, et intervenons dans la région selon la nature de la mission."],
  ["Proposez-vous des contrats d’entretien réguliers?", "Oui. Nous adaptons la fréquence à votre activité : passage quotidien, hebdomadaire, mensuel ou intervention ponctuelle."],
  ["Comment obtenir un devis?", "Appelez-nous ou écrivez-nous par email. Nous échangeons sur votre besoin et vous proposons une solution adaptée."],
];

function QuoteModal({ onClose }: { onClose: () => void }) {
  return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="quote-title"><div className="quote-modal"><button className="modal-close" onClick={onClose} aria-label="Fermer"><X size={20} /></button><div className="eyebrow">Demande gratuite</div><h2 id="quote-title">Parlons de votre besoin</h2><p>Indiquez-nous vos coordonnées et notre équipe vous recontactera rapidement.</p><form onSubmit={(e) => { e.preventDefault(); onClose(); }}><label>Votre nom<input required placeholder="Votre nom complet" /></label><label>Votre téléphone<input required type="tel" placeholder="+229 01 00 00 00 00" /></label><label>Votre besoin<select defaultValue=""><option value="" disabled>Choisissez un service</option>{services.map((service) => <option key={service.name}>{service.name}</option>)}</select></label><button className="button button-primary button-full" type="submit">Envoyer ma demande <ArrowRight size={16} /></button></form><div className="modal-note"><ShieldCheck size={15} /> Vos informations restent confidentielles</div></div></div>;
}

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [quoteOpen, setQuoteOpen] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const closeMenu = () => setMenuOpen(false);
  const openQuote = () => { setQuoteOpen(true); closeMenu(); };
  return <div className="site-shell">
    <header className="site-header"><a className="brand brand-card" href="#accueil" aria-label="Fassinou Services accueil"><img src={logo} alt="Fassinou Services" /></a><nav className={menuOpen ? "main-nav is-open" : "main-nav"} aria-label="Navigation principale"><a href="#services" onClick={closeMenu}>Nos services</a><a href="#methode" onClick={closeMenu}>Notre méthode</a><a href="#apropos" onClick={closeMenu}>À propos</a><a href="#faq" onClick={closeMenu}>FAQ</a><a className="phone-link" href="tel:+2290143446666"><PhoneCall size={13} /> +229 01 43 44 66 66</a><button className="button button-small button-primary" onClick={openQuote}>Demander un devis</button></nav><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Menu" aria-expanded={menuOpen}>{menuOpen ? <X size={23} /> : <Menu size={23} />}</button></header>
    <main>
      <section id="accueil" className="hero fassinou-hero"><div className="hero-overlay" /><div className="hero-photo" style={{ backgroundImage: `url(${products})` }} /><div className="hero-content"><div className="hero-kicker"><span /> FASSINOU SERVICES <span /></div><h1>Votre partenaire,<br /><em>propreté et hygiène.</em></h1><p>Nous prenons soin de vos espaces avec rigueur, discrétion et professionnalisme à Cotonou et ses environs.</p><div className="hero-actions"><button className="button button-primary" onClick={openQuote}>Demander un devis gratuit <ArrowRight size={16} /></button><a className="hero-phone" href="tel:+2290143446666">+229 01 43 44 66 66</a></div></div><a className="scroll-cue" href="#services" aria-label="Découvrir nos services"><span>Découvrir</span><ArrowDown size={17} /></a></section>
      <section id="services" className="section services-section"><div className="section-heading centered"><div className="eyebrow">Notre savoir-faire</div><h2>Des services pensés pour des espaces impeccables</h2><p>De l’entretien quotidien aux interventions spécialisées, Fassinou Services vous accompagne avec des solutions d’hygiène adaptées.</p></div><div className="services-layout"><div className="service-visual"><img className="main-service-image" src={cleaning} alt="Agent Fassinou Services en intervention" /><div className="image-badge"><Star size={17} fill="currentColor" /><span><strong>Qualité & rigueur</strong><small>Chaque détail compte</small></span></div></div><div className="service-cards">{services.map(({ icon: Icon, name, text }, index) => <article className={index === 0 ? "service-card featured" : "service-card"} key={name}><div className="service-icon"><Icon size={20} /></div><div><h3>{name}</h3><p>{text}</p></div><ArrowRight className="service-arrow" size={17} /></article>)}</div></div></section>
      <section className="promise-band"><div className="promise-image" style={{ backgroundImage: `url(${worker})` }} /><div className="promise-copy"><div className="eyebrow">Notre engagement</div><h2>La propreté qui se voit.<br /><span>La confiance qui reste.</span></h2><p>Notre équipe met son expertise et son énergie au service d’environnements sains, accueillants et durables.</p><div className="promise-list"><span><Check size={14} /> Personnel sérieux et formé</span><span><Check size={14} /> Produits et méthodes adaptés</span><span><Check size={14} /> Intervention discrète et ponctuelle</span></div><button className="text-button" onClick={openQuote}>Parler à notre équipe <ArrowRight size={16} /></button></div></section>
      <section id="methode" className="section method-section"><div className="section-heading centered"><div className="eyebrow">Notre méthode</div><h2>Un service simple, précis et humain</h2><p>Une organisation claire pour vous offrir une qualité constante à chaque passage.</p></div><div className="method-grid"><article><div className="number">01</div><h3>Écouter votre besoin</h3><p>Nous prenons le temps de comprendre vos espaces, vos contraintes et vos attentes.</p></article><article><div className="number">02</div><h3>Planifier la bonne intervention</h3><p>Nous choisissons le rythme, l’équipe et les méthodes les plus adaptés.</p></article><article><div className="number">03</div><h3>Garantir un résultat net</h3><p>Nous contrôlons chaque prestation pour que la qualité soit au rendez-vous.</p></article></div><div className="team-card"><img src={team} alt="Équipe Fassinou Services" /><div><div className="eyebrow">Une équipe engagée</div><h3>Des femmes et des hommes fiers de leur travail</h3><p>Votre satisfaction est notre meilleure recommandation.</p></div><button className="button button-outline" onClick={openQuote}>Nous contacter <ArrowRight size={16} /></button></div></section>
      <section id="apropos" className="section about-section"><div className="about-grid"><div><div className="eyebrow">Fassinou Services</div><h2>L’hygiène professionnelle, avec une attention particulière.</h2><p>Nous aidons les particuliers et les professionnels à garder des espaces propres, sains et agréables. Notre promesse : une présence fiable, un travail soigné et une relation de confiance.</p><div className="stats-row"><div><strong>5</strong><small>Expertises complémentaires</small></div><div><strong>100%</strong><small>Engagement terrain</small></div><div><strong>24/7</strong><small>À votre écoute</small></div></div></div><div className="about-card"><Droplets size={25} /><h3>Votre partenaire propreté et hygiène</h3><p>Entretien, nettoyage, remise en état, dératisation et désinsectisation : une seule équipe pour un environnement maîtrisé.</p><button className="text-button" onClick={openQuote}>Obtenir un devis <ArrowRight size={16} /></button></div></div></section>
      <section id="faq" className="section faq-section"><div className="faq-layout"><div className="section-heading"><div className="eyebrow">Questions fréquentes</div><h2>Tout ce que vous devez savoir</h2><p>Une question sur nos interventions? Notre équipe est disponible pour vous répondre.</p><a className="text-button" href="mailto:constantin8821@gmail.com">Écrire à l’équipe <Mail size={16} /></a></div><div className="faq-list">{faqs.map(([question, answer], index) => <div className={openFaq === index ? "faq-item is-open" : "faq-item"} key={question}><button onClick={() => setOpenFaq(openFaq === index ? null : index)} aria-expanded={openFaq === index}><span>{question}</span><ChevronDown size={18} /></button><div className="faq-answer"><p>{answer}</p></div></div>)}</div></div></section>
      <section className="final-cta"><div className="final-cta-inner"><div className="eyebrow">Un espace propre change tout</div><h2>Parlons de votre prochain<br /><span>besoin de propreté.</span></h2><p>Demandez votre devis et construisons ensemble la solution adaptée à votre environnement.</p><div className="guarantees"><span><ShieldCheck size={17} /> Réponse rapide</span><span><Clock3 size={17} /> Service professionnel</span></div><button className="button button-primary" onClick={openQuote}>Demander un devis gratuit <ArrowRight size={16} /></button></div></section>
    </main>
    <footer className="site-footer"><div className="footer-top"><div><a className="brand footer-brand brand-card" href="#accueil"><img src={logo} alt="Fassinou Services" /></a><p>Votre partenaire propreté et hygiène à Cotonou et dans ses environs.</p></div><div className="footer-column"><h4>Nos services</h4>{services.map((service) => <a href="#services" key={service.name}>{service.name}</a>)}</div><div className="footer-column"><h4>Nous joindre</h4><a href="tel:+2290143446666"><PhoneCall size={13} /> +229 01 43 44 66 66</a><a href="tel:+2290165754616"><PhoneCall size={13} /> +229 01 65 75 46 16</a><a href="mailto:constantin8821@gmail.com"><Mail size={13} /> constantin8821@gmail.com</a></div><div className="footer-column"><h4>Adresse</h4><span><MapPin size={13} /> Lot 1136, Parcelle NAV M/CHARLEMAGNE ZANNOU<br />Haie Vive, 12ème arrondissement<br />Cotonou, Bénin</span></div></div><div className="footer-bottom"><span>© 2025 Fassinou Services. Tous droits réservés.</span><span>IFU : 1201610181303 · RCCM RB / ABC / 17 A 5685</span></div></footer>
    {quoteOpen && <QuoteModal onClose={() => setQuoteOpen(false)} />}
  </div>;
}
